SELECT c.CAR_ID, c.CAR_TYPE, 
       ROUND(c.DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE)/100, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c 
LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY h 
    ON c.CAR_ID = h.CAR_ID 
    AND h.START_DATE <= '2022-11-30' AND h.END_DATE >= '2022-11-01'  -- ❌→✅ 기간 겹침
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
    ON c.CAR_TYPE = p.CAR_TYPE AND p.DURATION_TYPE = '30일 이상'
WHERE c.CAR_TYPE IN ('세단','SUV') 
  AND h.HISTORY_ID IS NULL  -- ❌→✅ LEFT JOIN 활용
  AND ROUND(c.DAILY_FEE * 30 * (100 - p.DISCOUNT_RATE)/100, 0) 
      BETWEEN 500000 AND 1999999  -- ❌→✅ FEE 반복 + 50만원
ORDER BY FEE DESC, c.CAR_TYPE ASC, c.CAR_ID DESC;
