WITH max_reviewers AS (
  SELECT MEMBER_ID
  FROM REST_REVIEW 
  GROUP BY MEMBER_ID 
  HAVING COUNT(*) = (
    SELECT MAX(review_cnt) 
    FROM (SELECT COUNT(*) AS review_cnt FROM REST_REVIEW GROUP BY MEMBER_ID) t
  )
)
SELECT 
  p.MEMBER_NAME, 
  r.REVIEW_TEXT, 
  DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW r 
JOIN MEMBER_PROFILE p ON r.MEMBER_ID = p.MEMBER_ID
JOIN max_reviewers t ON t.MEMBER_ID = r.MEMBER_ID
ORDER BY r.REVIEW_DATE, r.REVIEW_TEXT;
