with tmp as (
select year(DIFFERENTIATION_DATE) as YEAR , MAX(SIZE_OF_COLONY) as MAX_COLONY
from ECOLI_DATA 
group by year(DIFFERENTIATION_DATE)
)

select YEAR(E.DIFFERENTIATION_DATE) as YEAR, (T.MAX_COLONY - E.SIZE_OF_COLONY) as YEAR_DEV,E.ID 
from ECOLI_DATA E  join tmp T
on YEAR(E.DIFFERENTIATION_DATE) = T.YEAR
order by YEAR, YEAR_DEV