SELECT ID, FISH_NAME, LENGTH
FROM (
  SELECT I.ID, N.FISH_NAME, I.LENGTH,
         ROW_NUMBER() OVER(PARTITION BY I.FISH_TYPE ORDER BY I.LENGTH DESC) AS rn
  FROM FISH_INFO I 
  JOIN FISH_NAME_INFO N ON I.FISH_TYPE = N.FISH_TYPE
) t
WHERE rn = 1
ORDER BY ID;
